services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend_cache:/go/pkg/mod
    environment:
      - PORT=8080
      - DATABASE_URL=/app/data/game.db
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "1234:1234"
    volumes:
      - ./frontend:/app
      - frontend_cache:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  backend_cache:
  frontend_cache: